import AutoAwesomeOutlinedIcon from "@mui/icons-material/AutoAwesomeOutlined";
import CloseIcon from "@mui/icons-material/Close";
import RestartAltIcon from "@mui/icons-material/RestartAlt";
import {
  Box,
  Button,
  Card,
  Chip,
  Divider,
  IconButton,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Stack,
  Tooltip,
  Typography,
} from "@mui/material";
import CheckIcon from "@mui/icons-material/Check";
import type { ChatAdapter } from "@mui/x-chat-headless";

import FormAssistantChat from "./FormAssistantChat";

interface ChatPanelProps {
  onClose: () => void;
  onReset: () => void;
  adapter: ChatAdapter;
  sessionKey: string;
  formTitle: string;
  status: "Draft" | "Live";
  proposalSummary?: string[];
  onReviewProposal?: () => void;
  onApplyProposal?: () => void;
  onDismissProposal?: () => void;
  showClose?: boolean;
}

export const ChatPanel = ({
  onClose,
  onReset,
  adapter,
  sessionKey,
  formTitle,
  status,
  proposalSummary = [],
  onReviewProposal,
  onApplyProposal,
  onDismissProposal,
  showClose = true,
}: ChatPanelProps) => (
  <Box
    sx={{
      height: "100%",
      minHeight: 0,
      width: "100%",
      display: "flex",
      flexDirection: "column",
      bgcolor: "background.paper",
    }}
  >
    <Stack
      direction="row"
      alignItems="center"
      justifyContent="space-between"
      spacing={1}
      sx={{ minHeight: 56, px: 2, borderBottom: "1px solid", borderColor: "divider" }}
    >
      <Stack direction="row" spacing={1} alignItems="center">
        <AutoAwesomeOutlinedIcon color="secondary" fontSize="small" />
        <Typography variant="subtitle1">Assistant</Typography>
      </Stack>

      <Stack direction="row" alignItems="center" spacing={0.5}>
        <Tooltip title="Start a new chat">
          <IconButton onClick={onReset} aria-label="Start a new chat">
            <RestartAltIcon fontSize="small" />
          </IconButton>
        </Tooltip>
        {showClose && (
          <Tooltip title="Close assistant">
            <IconButton onClick={onClose} aria-label="Close assistant">
              <CloseIcon fontSize="small" />
            </IconButton>
          </Tooltip>
        )}
      </Stack>
    </Stack>

    <Stack
      direction="row"
      spacing={1}
      alignItems="center"
      sx={{
        px: 2,
        py: 1.25,
        bgcolor: "secondary.light",
        borderBottom: "1px solid",
        borderColor: "divider",
      }}
    >
      <Typography variant="caption" color="secondary.dark" sx={{ flex: 1 }} noWrap>
        Working on: {formTitle.trim() || "Untitled form"}
      </Typography>
      <Chip
        size="small"
        label={status}
        sx={{ bgcolor: "background.paper", color: "secondary.dark" }}
      />
    </Stack>

    {proposalSummary.length > 0 && (
      <Box sx={{ p: 1.5, borderBottom: "1px solid", borderColor: "divider" }}>
        <Card
          sx={{
            p: 1.5,
            borderColor: "secondary.main",
            bgcolor: "secondary.light",
          }}
        >
          <Stack spacing={1.25}>
            <Box>
              <Typography variant="subtitle2">Suggested changes</Typography>
              <Typography variant="caption" color="text.secondary">
                Generated by AI · Review before applying
              </Typography>
            </Box>
            <List dense disablePadding>
              {proposalSummary.map((item) => (
                <ListItem key={item} disableGutters sx={{ py: 0.15 }}>
                  <ListItemIcon sx={{ minWidth: 28, color: "secondary.main" }}>
                    <CheckIcon fontSize="small" />
                  </ListItemIcon>
                  <ListItemText
                    primary={item}
                    slotProps={{ primary: { variant: "body2" } }}
                  />
                </ListItem>
              ))}
            </List>
            <Divider />
            <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
              {onReviewProposal && (
                <Button
                  type="button"
                  variant="outlined"
                  color="secondary"
                  onClick={onReviewProposal}
                >
                  Review changes
                </Button>
              )}
              <Button
                type="button"
                variant="contained"
                color="secondary"
                onClick={onApplyProposal}
                sx={{ flex: 1, minWidth: 132 }}
              >
                Apply changes
              </Button>
              <Button type="button" variant="outlined" onClick={onDismissProposal}>
                Dismiss
              </Button>
            </Stack>
          </Stack>
        </Card>
      </Box>
    )}

    <Box sx={{ flex: 1, minHeight: 0 }}>
      <FormAssistantChat adapter={adapter} sessionKey={sessionKey} />
    </Box>
  </Box>
);
