import CheckRoundedIcon from "@mui/icons-material/CheckRounded";
import CloseRoundedIcon from "@mui/icons-material/CloseRounded";
import RestartAltRoundedIcon from "@mui/icons-material/RestartAltRounded";
import SettingsRoundedIcon from "@mui/icons-material/SettingsRounded";
import {
  Box,
  Button,
  Card,
  Chip,
  Divider,
  IconButton,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Stack,
  Tooltip,
  Typography,
} from "@mui/material";
import type { ChatAdapter } from "@mui/x-chat-headless";

import FormAssistantChat from "./FormAssistantChat";

interface ChatPanelProps {
  onClose: () => void;
  onReset: () => void;
  adapter: ChatAdapter;
  sessionKey: string;
  formTitle: string;
  status: "Draft" | "Live" | "Ready";
  mode?: "form" | "overview";
  assistantDescription?: string;
  contextLabel?: string;
  proposalSummary?: string[];
  proposalTitle?: string;
  proposalDescription?: string;
  applyProposalLabel?: string;
  onReviewProposal?: () => void;
  onApplyProposal?: () => void;
  onDismissProposal?: () => void;
  showClose?: boolean;
}

const GearCluster = () => (
  <Box
    aria-hidden="true"
    sx={{
      position: "relative",
      width: 48,
      height: 48,
      flex: "0 0 48px",
      borderRadius: "15px",
      bgcolor: "rgba(255,255,255,0.10)",
      border: "1px solid rgba(255,255,255,0.16)",
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.12)",
    }}
  >
    <SettingsRoundedIcon
      sx={{
        position: "absolute",
        insetInlineStart: 7,
        insetBlockStart: 7,
        width: 27,
        height: 27,
        color: "#C9C4FF",
        animation: "assistant-gear-clockwise 8s linear infinite",
      }}
    />
    <SettingsRoundedIcon
      sx={{
        position: "absolute",
        insetInlineEnd: 5,
        insetBlockEnd: 5,
        width: 20,
        height: 20,
        color: "#FFFFFF",
        animation: "assistant-gear-counter 11s linear infinite",
      }}
    />
  </Box>
);

export const ChatPanel = ({
  onClose,
  onReset,
  adapter,
  sessionKey,
  formTitle,
  status,
  mode = "form",
  assistantDescription = "Reviews the current form and proposes changes",
  contextLabel = "Current form",
  proposalSummary = [],
  proposalTitle = "Proposed form changes",
  proposalDescription = "Generated by AI · Nothing changes until you approve",
  applyProposalLabel = "Apply changes",
  onReviewProposal,
  onApplyProposal,
  onDismissProposal,
  showClose = true,
}: ChatPanelProps) => (
  <Box
    sx={{
      height: "100%",
      minHeight: 0,
      width: "100%",
      display: "flex",
      flexDirection: "column",
      bgcolor: "#FBFAFF",
    }}
  >
    <Stack
      direction="row"
      alignItems="center"
      spacing={1.5}
      sx={{
        minHeight: 78,
        px: { xs: 1.5, sm: 2.25 },
        py: 1.5,
        color: "common.white",
        background:
          "linear-gradient(128deg, #1E1650 0%, #2D216C 58%, #4B3ED2 100%)",
        boxShadow: "0 10px 30px rgba(30, 22, 80, 0.22)",
        zIndex: 1,
      }}
    >
      <GearCluster />

      <Box sx={{ flex: 1, minWidth: 0 }}>
        <Typography
          component="h2"
          sx={{
            fontSize: "1rem",
            lineHeight: 1.3,
            fontWeight: 760,
            letterSpacing: "-0.02em",
          }}
        >
          FormFlow Assistant
        </Typography>
        <Typography
          variant="caption"
          sx={{ display: "block", mt: 0.25, color: "rgba(255,255,255,0.68)" }}
        >
          {assistantDescription}
        </Typography>
      </Box>

      <Stack direction="row" alignItems="center" spacing={0.25}>
        <Tooltip title="Start a new conversation">
          <IconButton
            onClick={onReset}
            aria-label="Start a new conversation"
            sx={{
              color: "rgba(255,255,255,0.82)",
              "&:hover": { bgcolor: "rgba(255,255,255,0.10)" },
            }}
          >
            <RestartAltRoundedIcon fontSize="small" />
          </IconButton>
        </Tooltip>
        {showClose && (
          <Tooltip title="Close assistant">
            <IconButton
              onClick={onClose}
              aria-label="Close assistant"
              sx={{
                color: "common.white",
                "&:hover": { bgcolor: "rgba(255,255,255,0.10)" },
              }}
            >
              <CloseRoundedIcon fontSize="small" />
            </IconButton>
          </Tooltip>
        )}
      </Stack>
    </Stack>

    <Stack
      direction="row"
      spacing={1.25}
      alignItems="center"
      sx={{
        px: { xs: 1.75, sm: 2.5 },
        py: 1.25,
        bgcolor: "background.paper",
        borderBottom: "1px solid",
        borderColor: "divider",
      }}
    >
      <Box sx={{ flex: 1, minWidth: 0 }}>
        <Typography
          sx={{
            fontFamily: '"JetBrains Mono", monospace',
            fontSize: "0.62rem",
            lineHeight: 1.4,
            fontWeight: 600,
            letterSpacing: "0.1em",
            color: "primary.main",
            textTransform: "uppercase",
          }}
        >
          {contextLabel}
        </Typography>
        <Typography
          variant="body2"
          sx={{ mt: 0.2, fontWeight: 650 }}
          title={formTitle.trim() || "Untitled form"}
          noWrap
        >
          {formTitle.trim() || "Untitled form"}
        </Typography>
      </Box>
      <Chip
        size="small"
        label={status}
        sx={{
          bgcolor:
            status === "Live"
              ? "success.light"
              : status === "Ready"
                ? "secondary.light"
                : "primary.light",
          color:
            status === "Live"
              ? "success.dark"
              : status === "Ready"
                ? "secondary.main"
                : "primary.dark",
          border: "1px solid",
          borderColor:
            status === "Live"
              ? "success.main"
              : status === "Ready"
                ? "secondary.main"
                : "primary.main",
          fontFamily: '"JetBrains Mono", monospace',
          fontSize: "0.66rem",
          letterSpacing: "0.06em",
          textTransform: "uppercase",
        }}
      />
    </Stack>

    {proposalSummary.length > 0 && (
      <Box sx={{ p: 1.5, borderBottom: "1px solid", borderColor: "divider" }}>
        <Card
          sx={{
            p: 1.75,
            borderColor: "primary.main",
            bgcolor: "primary.light",
            boxShadow: "0 8px 24px rgba(91, 80, 247, 0.10)",
          }}
        >
          <Stack spacing={1.25}>
            <Box>
              <Typography component="h3" variant="subtitle2">
                {proposalTitle}
              </Typography>
              <Typography variant="caption" color="text.secondary">
                {proposalDescription}
              </Typography>
            </Box>
            <List dense disablePadding>
              {proposalSummary.map((item) => (
                <ListItem key={item} disableGutters sx={{ py: 0.2 }}>
                  <ListItemIcon sx={{ minWidth: 28, color: "primary.main" }}>
                    <CheckRoundedIcon fontSize="small" />
                  </ListItemIcon>
                  <ListItemText
                    primary={item}
                    slotProps={{ primary: { variant: "body2" } }}
                  />
                </ListItem>
              ))}
            </List>
            <Divider />
            <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
              {onReviewProposal && (
                <Button
                  type="button"
                  variant="outlined"
                  onClick={onReviewProposal}
                >
                  Review changes
                </Button>
              )}
              <Button
                type="button"
                variant="contained"
                onClick={onApplyProposal}
                sx={{ flex: 1, minWidth: 132 }}
              >
                {applyProposalLabel}
              </Button>
              <Button type="button" variant="text" onClick={onDismissProposal}>
                Dismiss
              </Button>
            </Stack>
          </Stack>
        </Card>
      </Box>
    )}

    <Box sx={{ flex: 1, minHeight: 0 }}>
      <FormAssistantChat
        adapter={adapter}
        sessionKey={sessionKey}
        mode={mode}
      />
    </Box>
  </Box>
);
